var ECTableMessage={
	ENCODING		: "UTF-8",
	WAITTING_MSG	: "is submitting...",
	FILTERCLEAR_TEXT: "FLITERCLEAR",
	SORTASC_TEXT	: "SORRASC",
	SORTDESC_TEXT	: "SORTDESC",
	SORTDEFAULT_TEXT: "SORTDEFAULT",
	ERR_PAGENO		: "PAGENO IS 1 TO #{1} !",
	EXPORT_CONFIRM	: "EXPORT ALL DATA?\n\n( \"CANCALE\" EXPORT CURRENT PAGE)",
	OVER_MAXEXPORT	: "OVER_MAXEXPORT ( #{1} RECORD ).",
	SHADOWROW_FAILED: "	NO INFO",
	NO_RECORD_UPDATE: "NO RECORT UPDATE!",
	UPDATE_CONFIRM	: "ARE YOU SURE TO SAVE?",
	NEARPAGE_TITLE	: ""
};